#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

s3rver-destroy-cmd() {
  declare desc="delete a bucket from $PLUGIN_SERVICE service"
  local cmd="$PLUGIN_COMMAND_PREFIX:bucket:destroy" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"
  declare BUCKET="$2"
  service_destroy_bucket "$SERVICE" "$BUCKET"
}

s3rver-destroy-cmd "$@"
