#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

s3rver-list-buckets-cmd() {
  declare desc="list all $PLUGIN_SERVICE buckets under service"
  local cmd="$PLUGIN_COMMAND_PREFIX:bucket:list" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  service_list_buckets "$SERVICE"
}

s3rver-list-buckets-cmd "$@"
